version: "3.8"
services:
  caddy:
    labels:
      # For Docker Compose Traefik Deployment (single node)
      - traefik.enable=true
      - traefik.http.routers.caddy.rule=Host(`${HOST:-caddy-127-0-0-1.nip.io}`)
      - traefik.http.routers.caddy.entrypoints=http,https
      - traefik.http.routers.caddy.tls.certresolver=le
