version: "3.6"
services:
  example:
    image: ondrejsika/go-hello-world:2
    networks:
      - traefik
    labels:
      # For Docker Compose Traefik Deployment (single node)
      - "traefik.enable=true"
      - "traefik.http.routers.${ROUTER_NAME:-hello-world}.rule=Host(`${HOST:-hello-127-0-0-1.nip.io}`)"
      # - "traefik.http.routers.${ROUTER_NAME:-hello-world}.entrypoints=http"

networks:
  traefik:
    external:
      name: traefik
