version: "3.8"
services:
  nginx:
    image: nginx
    networks:
      - traefik
    labels:
      # For Docker Compose Traefik Deployment (single node)
      - "traefik.enable=true"
      - "traefik.http.routers.${ROUTER_NAME:-nginx}.rule=Host(`${HOST:-nginx-127-0-0-1.nip.io}`)"
      # - "traefik.http.routers.${ROUTER_NAME:-nginx}.entrypoints=http,https"

networks:
  traefik:
    external:
      name: traefik
